version: '3'
services:
  mongo-peluqueria:
    image: mongo:latest
    container_name: mongo-peluqueria-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: peluqueriaDB
